# This file is generated by 'make build' and should not be edited

MAJOR = 2
MINOR = 0
PATCH = 0

ESP_HASH = "fd11e627643201da15389c0768f0fde0bae4024f"
RPI_HASH = "1dd09d5d3f198f74fb6fcc3145f3c5d36bda7b9b"
