# This file is generated by 'make build' and should not be edited

MAJOR = 2
MINOR = 0
PATCH = 0

ESP_HASH = "9476dd56d2dad50ab9c3bc2070cd018db495d3f3"
RPI_HASH = "d58a87daf9f13b395500166833e45d061cf9b85d"
