// This file was auto generated by config_generator at 2021-10-26 19:59:00.772329
// DO NOT EDIT THIS FILE

#ifndef CONFIG_H_
#define CONFIG_H_

constexpr int UDP_PORT = 8000;
constexpr int ACK_PORT = 8001;
constexpr int PACKET_BUFFER_SIZE = 2048;
constexpr int MAX_BRIGHTNESS = 127;
constexpr float BRIGHTNESS_MULTIPLIER = 0.5;
constexpr bool DEBUG_PRINT = true;

constexpr int INIT_BRIGHTNESS = 100;
constexpr int INIT_FRAME_MS = 30;
constexpr int INIT_FRAME_MULTIPLIER = 1;

// CONSTANTS
constexpr int MAX_LED = 300;
constexpr int LIST_CAPACITY = 500;
constexpr int BITS_PER_BYTE = 8;
constexpr int BITS_PER_USAGE_FLAG = 32;
constexpr int ITEMS_PER_COLOR_BLOCK = 8;
constexpr int MAX_PIXELS_PER_FRAME = 320;

#endif  // CONFIG_H_
