// This file is generated by 'make build' and should not be edited

#define MAJOR 2
#define MINOR 0
#define PATCH 0

#define ESP_HASH "9476dd56d2dad50ab9c3bc2070cd018db495d3f3"
#define RPI_HASH "289868b38c9d267c002280cebe036f539ca1c5d3"
