// This file is generated by 'make build' and should not be edited

#define MAJOR 2
#define MINOR 0
#define PATCH 0

#define ESP_HASH "5d0730910d0ac5316205341d9e9382408b430a29"
#define RPI_HASH "289868b38c9d267c002280cebe036f539ca1c5d3"
