// This file is generated by 'make build' and should not be edited

#define MAJOR 2
#define MINOR 0
#define PATCH 0

#define ESP_HASH "5be1fe05cdde03245ef35ab0eca3191054483161"
#define RPI_HASH "3ff89fd88b28118668683b9b0edff412d892d59d"
