/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev at Mon Nov  1 16:27:02 2021. */

#include "animation.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AnimationArgs, AnimationArgs, AUTO)


PB_BIND(ListMax25, ListMax25, AUTO)


PB_BIND(Frame, Frame, 2)


PB_BIND(Brightness, Brightness, AUTO)


PB_BIND(LEDInfo, LEDInfo, AUTO)




