/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev at Wed Nov  3 19:43:15 2021. */

#include "packet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Packet, Packet, 2)


PB_BIND(Payload, Payload, 2)


PB_BIND(Header, Header, AUTO)


PB_BIND(Options, Options, AUTO)


PB_BIND(ESPInfo, ESPInfo, AUTO)


PB_BIND(Version, Version, AUTO)


PB_BIND(Hash, Hash, AUTO)


PB_BIND(LogMessage, LogMessage, 2)





